jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b
      with:
        ref: 1.1.x
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: '8'
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew clean check --no-daemon -PforceTransport=nio -PreactorCoreVersion='3.6.6-SNAPSHOT'
        -PforceContextPropagationVersion='1.1.0'
name: Check Reactor Netty 1.1.x with Reactor Core 3.6 SNAPSHOTS
on:
  repository_dispatch:
    types: trigger-ga___check_reactor_core_3.6_snapshots.yml
permissions: read-all
