env:
  DOCS_BUILD_ARTIFACT: docs-build
jobs:
  build-branch-doc:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b
    - continue-on-error: true
      name: Set up Ruby for asciidoctor-pdf
      uses: ruby/setup-ruby@cacc9f1c0b3f4eb8a16a6bb0ed10897b43b9de49
      with:
        ruby-version: 3.3.0
    - continue-on-error: true
      name: Install asciidoctor-pdf / rouge
      run: gem install asciidoctor-pdf rouge
    - continue-on-error: true
      name: Setup java 17 for antora
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Build antora doc for the current branch
      run: ./gradlew antora
    - continue-on-error: true
      name: Copy the cache to be included in the site
      run: '[ -d docs/build/antora/inject-collector-cache-config-extension/.cache
        ] && cp -rf docs/build/antora/inject-collector-cache-config-extension/.cache
        docs/build/site/'
    - continue-on-error: true
      name: Upload docs/build to current workflow run
      uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808
      with:
        if-no-files-found: error
        name: ${{ env.DOCS_BUILD_ARTIFACT }}
        path: docs/build
        retention-days: 1
  cleanup:
    if: always()
    needs:
    - reactor-netty-core
    - tagRelease
    - tagMilestone
    - deploySnapshot
    permissions:
      actions: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: delete antora docs-build artifact
      run: "ARTIFACTS_URL=\"/repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/artifacts\"\
        \nARTIFACT_ID=$(gh api -H 'Accept: application/vnd.github+json' -H 'X-GitHub-Api-Version:\
        \ 2022-11-28' $ARTIFACTS_URL | jq -r '.artifacts[] | select(.name == \"'$DOCS_BUILD_ARTIFACT'\"\
        ) | .id // \"\"')\nif [ -n \"$ARTIFACT_ID\" ]; then\n  gh api --method DELETE\
        \ -H 'Accept: application/vnd.github+json' -H 'X-GitHub-Api-Version: 2022-11-28'\
        \ /repos/${{github.repository}}/actions/artifacts/$ARTIFACT_ID}\nfi"
  deployMilestone:
    environment: releases
    if: needs.reactor-netty-core.outputs.versionType == 'MILESTONE'
    name: deployMilestone
    needs:
    - reactor-netty-core
    - reactor-netty-http
    - reactor-netty-http-brave
    - reactor-netty-incubator-quic
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b
    - continue-on-error: true
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: '8'
    - continue-on-error: true
      name: download antora docs/build
      uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e
      with:
        name: ${{ env.DOCS_BUILD_ARTIFACT }}
        path: docs/build
    - continue-on-error: true
      env:
        ORG_GRADLE_PROJECT_artifactory_publish_password: ${{secrets.ARTIFACTORY_PASSWORD}}
        ORG_GRADLE_PROJECT_artifactory_publish_username: ${{secrets.ARTIFACTORY_USERNAME}}
        ORG_GRADLE_PROJECT_signingKey: ${{secrets.SIGNING_KEY}}
        ORG_GRADLE_PROJECT_signingPassword: ${{secrets.SIGNING_PASSPHRASE}}
      name: deploy
      run: './gradlew assemble sign artifactoryPublish -Partifactory_publish_contextUrl=https://repo.spring.io
        -Partifactory_publish_repoKey=libs-milestone-local

        '
  deployRelease:
    environment: releases
    if: needs.reactor-netty-core.outputs.versionType == 'RELEASE'
    name: deployRelease
    needs:
    - reactor-netty-core
    - reactor-netty-http
    - reactor-netty-http-brave
    - reactor-netty-incubator-quic
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b
    - continue-on-error: true
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: '8'
    - continue-on-error: true
      name: download antora docs/build
      uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e
      with:
        name: ${{ env.DOCS_BUILD_ARTIFACT }}
        path: docs/build
    - continue-on-error: true
      env:
        ORG_GRADLE_PROJECT_artifactory_publish_password: ${{secrets.ARTIFACTORY_PASSWORD}}
        ORG_GRADLE_PROJECT_artifactory_publish_username: ${{secrets.ARTIFACTORY_USERNAME}}
        ORG_GRADLE_PROJECT_signingKey: ${{secrets.SIGNING_KEY}}
        ORG_GRADLE_PROJECT_signingPassword: ${{secrets.SIGNING_PASSPHRASE}}
        ORG_GRADLE_PROJECT_sonatypePassword: ${{secrets.SONATYPE_PASSWORD}}
        ORG_GRADLE_PROJECT_sonatypeUsername: ${{secrets.SONATYPE_USERNAME}}
      name: deploy
      run: './gradlew assemble sign artifactoryPublish -Partifactory_publish_contextUrl=https://repo.spring.io  -Partifactory_publish_repoKey=libs-release-local
        publishMavenJavaPublicationToSonatypeRepository

        '
  deploySnapshot:
    environment: snapshots
    if: needs.reactor-netty-core.outputs.versionType == 'SNAPSHOT'
    name: deploySnapshot
    needs:
    - reactor-netty-core
    - reactor-netty-http
    - reactor-netty-http-brave
    - reactor-netty-incubator-quic
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b
    - continue-on-error: true
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: '8'
    - continue-on-error: true
      name: download antora docs/build
      uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e
      with:
        name: ${{ env.DOCS_BUILD_ARTIFACT }}
        path: docs/build
    - continue-on-error: true
      env:
        ORG_GRADLE_PROJECT_artifactory_publish_password: ${{secrets.ARTIFACTORY_PASSWORD}}
        ORG_GRADLE_PROJECT_artifactory_publish_username: ${{secrets.ARTIFACTORY_SNAPSHOT_USERNAME}}
      name: deploy
      run: './gradlew assemble artifactoryPublish -Partifactory_publish_contextUrl=https://repo.spring.io
        -Partifactory_publish_repoKey=libs-snapshot-local

        '
  reactor-netty-core:
    name: reactor-netty-core
    outputs:
      fullVersion: ${{ steps.version.outputs.fullVersion }}
      versionType: ${{ steps.version.outputs.versionType }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b
    - continue-on-error: true
      name: setup java
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: '8'
    - continue-on-error: true
      id: version
      name: interpret version
      run: ./gradlew qualifyVersionGha
    - continue-on-error: true
      id: reactor-netty-core-checks
      name: run reactor-netty-core checks
      run: ./gradlew reactor-netty-core:check
  reactor-netty-http:
    name: reactor-netty-http
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b
    - continue-on-error: true
      name: setup java
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: '8'
    - continue-on-error: true
      id: reactor-netty-http-checks
      name: run reactor-netty-http checks
      run: ./gradlew reactor-netty-http:check
  reactor-netty-http-brave:
    name: reactor-netty-http-brave
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b
    - continue-on-error: true
      name: setup java
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: '8'
    - continue-on-error: true
      id: reactor-netty-http-brave-checks
      name: run reactor-netty-http-brave checks
      run: ./gradlew reactor-netty-http-brave:check
  reactor-netty-incubator-quic:
    name: reactor-netty-incubator-quic
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b
    - continue-on-error: true
      name: setup java
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: '8'
    - continue-on-error: true
      id: reactor-netty-incubator-quic-checks
      name: run reactor-netty-incubator-quic checks
      run: ./gradlew reactor-netty-incubator-quic:check
  tagMilestone:
    name: Tag milestone
    needs:
    - reactor-netty-core
    - deployMilestone
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b
    - continue-on-error: true
      name: tag
      run: 'git config --local user.name ''reactorbot''

        git config --local user.email ''32325210+reactorbot@users.noreply.github.com''

        git tag -m "Release milestone ${{ needs.reactor-netty-core.outputs.fullVersion
        }}" v${{ needs.reactor-netty-core.outputs.fullVersion }} ${{ github.sha }}

        git push --tags

        '
  tagRelease:
    name: Tag release
    needs:
    - reactor-netty-core
    - deployRelease
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b
    - continue-on-error: true
      name: tag
      run: 'git config --local user.name ''reactorbot''

        git config --local user.email ''32325210+reactorbot@users.noreply.github.com''

        git tag -m "Release version ${{ needs.reactor-netty-core.outputs.fullVersion
        }}" v${{ needs.reactor-netty-core.outputs.fullVersion }} ${{ github.sha }}

        git push --tags

        '
name: publish
on:
  repository_dispatch:
    types: trigger-ga___publish.yml
permissions: read-all
